name: Generate Pacman Contribution Graph

on:
  workflow_dispatch: # allows you to trigger manually
  schedule:
    - cron: "0 0 * * *" # runs once a day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pacman graph
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: pranavmarjara  # 👈 change if needed

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: update pacman contribution graph" || echo "No changes to commit"
          git push

